---
-
 hosts: centos1
 user: root
 vars:
 tasks:
   - name: Checking variable from host centos1
     debug:
       msg: "{{ hostvars[ansible_hostname].ansible_port }}"

         
   - name: Checking IP address
     debug:
       msg: "{{ hostvars[ansible_hostname].ansible_default_ipv4.address }}"


   - name: Date time from gather_facts ...setup module
     debug:
       msg: "Today date and time : {{ hostvars[ansible_hostname].ansible_date_time.date, hostvars[ansible_hostname].ansible_date_time.time }}"
...
