---
-
 hosts: all
 user: root
 gather_facts: False
 vars:
   motd: "Welcome to OS sections --- > Onkar"
 tasks:
  - name: copy modt to remote machine
    copy:
      content: "{{ motd }}"
      dest: /etc/motd


